### ISSUE TITLE
old cutechess needs qt4

### ISSUE THREAD

**Issue by tryingsomestuff** [AndyGrant/OpenBench#71] opened 2020-05-28 13:32 UTC
the given cutechess for linux need qt4 core (and gui) lib. There are no longer available on debian nor ubuntu. 
Two solutions : 
- provide a qt5 compiled cutechess 
- or put both qt4core and qt4gui .so file near the given cutechess.

**Comment by tryingsomestuff** [comment] 2020-05-30 11:11
oops just saw the other issue and the PR.
For me, just unpacking
https://packages.ubuntu.com/eoan/amd64/libqtcore4/download
and
https://packages.ubuntu.com/eoan/amd64/libqtgui4/download
near cutechess is working 
```
cutechess
libcutechess.so.1
libQtCLucene.so.4
libQtCLucene.so.4.8
libQtCLucene.so.4.8.7
libQtCore.so.4
libQtCore.so.4.8
libQtCore.so.4.8.7
libQtGui.so.4
libQtGui.so.4.8
libQtGui.so.4.8.7
```

**Comment by AndyGrant** [comment] 2020-09-07 05:33
Closed as duplicate of https://github.com/AndyGrant/OpenBench/issues/39

**Closed by AndyGrant** 2020-09-07 05:33 UTC
